### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yuntai** [juancamilocampos/nfl-big-data-bowl-2020#1]
Thanks for the great repo! I was trying to reprdouce the #1 solution but not easy until I found your repo. Regarding `0.011911` you got, did you ensemble the best models from CV (8 best from each fold?) Thank you!

**Comment by juancamilocampos** [comment]
Hi @yuntai. For the score `0.011911` I ensemble the best models from CV, but I only used 6 folds. Furthermore, another main difference with the original winner solution is that I am not using `one cycle scheduler` to adjust the learning rate. Please refer to link to find my kaggle notebook https://www.kaggle.com/jccampos/nfl-2020-winner-solution-the-zoo 
Please let me know if you another question or feedback
